# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2587dc01d19bb12e2f05512cbbc165215996bba6c9f404be03fbe84981d3b8f22392e5763606475a14c0fbb877cebe73ea95fc5553bdb3b9ec00df0693c007e8

test:
  secret_key_base: a689be708f6da5361f386aaac5aa8ed279d9f8387dcc705ae391bbb8bcbb20f559eb56e3b144fe30a7d6dd94d202401ada72fdb1bb3ee871e650cec9e5581f81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
